# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 05:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0013_urlconfrevision'),
        ('filer', '0002_auto_20150606_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=512, validators=[django.core.validators.URLValidator()])),
                ('caption', models.TextField(blank=True)),
                ('quality', models.IntegerField(choices=[(0, 'Original'), (1, 'High (for full-page images)'), (2, 'Medium (large images)'), (3, 'Low (best for smaller images shown in a side column)')], default=2)),
                ('template', models.IntegerField(choices=[(0, 'Fit to width of container'), (1, 'Float to the left'), (2, 'Float to the right')], default=2, verbose_name='Position')),
                ('frame', models.BooleanField(default=True, verbose_name='Border')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
