# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-21 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesettings',
            name='frame',
            field=models.BooleanField(default=False, verbose_name='Border'),
        ),
        migrations.AlterField(
            model_name='imagesettings',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Original'), (1, 'High (for full-page images)'), (2, 'Medium (large images)'), (3, 'Low (best for smaller images shown in a side column)')], default=0),
        ),
        migrations.AlterField(
            model_name='imagesettings',
            name='template',
            field=models.IntegerField(choices=[(0, 'Left, fit within container'), (3, 'Center within container'), (1, 'Float to the left'), (2, 'Float to the right')], default=0, verbose_name='Position'),
        ),
    ]
