# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-21 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_img', '0002_new_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesettings',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_img_imagesettings', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
