# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_urlconfrevision'),
        ('filer', '0002_auto_20150606_2003'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RenameField(
            model_name='pagesection',
            old_name='visible',
            new_name='show_header',
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='show_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='fragment_id',
            field=models.SlugField(default='main', help_text='A short, unique, no-spaces, word or phrase that will appear in the URL if people link directly to this section.', max_length=32, verbose_name='ID'),
        ),
    ]
