# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-21 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_backgroundimage', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_pagesection', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_partner', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
