# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0013_urlconfrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('desc', models.CharField(blank=True, max_length=300, verbose_name='Description (hidden)')),
                ('html', models.TextField(blank=True, verbose_name='HTML')),
                ('css', models.TextField(blank=True, verbose_name='CSS')),
                ('js', models.TextField(blank=True, verbose_name='Javascript')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
