# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0002_auto_20150606_2003'),
        ('cms', '0013_urlconfrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureImageExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('feature_image', filer.fields.image.FilerImageField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='cms_extensions.FeatureImageExtension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
