# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0002_auto_20150606_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engage_id', models.IntegerField(help_text="The vehicle's ID/# as seen in Engage.", unique=True, verbose_name='Car #')),
                ('name', models.CharField(help_text='Name is not shown to visitors, since the name from Engage is used.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Details',
            },
        ),
    ]
